# Run commands
# $ docker-compose up -d
# $ docker-compose up --build
# $ docker-compose down
# $ docker ps 
# access browser via http://127.0.0.1:8000 or localhost:8000
# Log into SQL hosted in a container
# $ winpty docker exec -it mysql mysql -u root -p
# Log into shell of a RUNNING container (using GIT BASH)
# $ winpty docker exec -t -i <my-container-name> sh

name: docker-python-mysql

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # When container is first created, this database and superuser are created
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - 3308:3306
    volumes:
     
      - ./sql:/media # Shared folder, just in case
      - ./sql:/docker-entrypoint-initdb.d:rw # Scripts in this folder are run automatically at container creation
      # - ./sql/data:/var/lib/mysql # MySQL data folder
      
  web:    # Running our app.py 
    build: .
    ports:
        # HOST:CONTAINER
      - "8000:5000"  # http://127.0.0.1:8000
    depends_on:
      - db
      
  redis:    # in-memory, key-value data store. More details: https://registry.hub.docker.com/_/redis/
    image: "redis:alpine"
    