# change the properties below as per your environment
connection_from_host:  
  host: 'host.docker.internal'  # connecting MySQL server of the host machine 
  port: '3306'
  database: 'world' 
  user: 'root'
  password: 'admin'
  raise_on_warnings: True

connection_from_container:
  host: 'db'  # connecting MySQL server defined as a service in the docker compose.yml
  port: '3306'
  database: 'testdb'
  user: 'root'
  password: 'root'
  raise_on_warnings: True